### ISSUE TITLE
Socket hang up error

### ISSUE THREAD

**Issue by robhawkes** [polygon-city/building-database-kml-importer#1]
I'm seeing what seems to be unpredictable socket hang up errors when processing batches of large KML files.

```
Error: socket hang up
    at createHangUpError (http.js:1477:15)
    at Socket.socketOnEnd [as onend] (http.js:1573:23)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
```

There doesn't seem to be a consistent trigger, as when running the same dataset multiple times I saw it occur after 55 buildings the first time and after 200 the second.

From what I can see, it may be caused by:
- My shoddy Internet connection causing a timeout to occur before a building has finished uploading
- My shoddy Internet connection causing the upload to drop midway and cause an unhandled error (though there is no error on the server)
- The server not closing the connection under some circumstance
- The client not handling the server response properly under some circumstance

I'm not sure which it is yet, if any of them, though my money is on the first option.

**Comment by robhawkes** [comment]
I'm wondering if the addition of background uploading in v2 of PolygonCity will help here. Background uploading will return a success response as soon as a building has been sent to the server for processing, meaning it could prevent this socket hang up occurring in the first place. It would certainly add more complexity however as you'd need to poll the server to check on the upload state so further action can be performed when the upload has completed.

**Comment by robhawkes** [comment]
While the socket errors are still occurring periodically, the batch functionality added in #2 has meant that it's possible to resume the addition of buildings and pick up where you left of. I also noticed that the socket hangup can occur even for successful building uploads, so I'm still not entirely sure what could be causing it yet.

**Comment by robhawkes** [comment]
It looks like this could also be related to a Node issue with HTTP: https://github.com/Automattic/knox/blob/master/lib/client.js#L233

One potential fix to try is upping the max sockets values, eg:

```
var http = require("http");
var https = require("https");

http.globalAgent.maxSockets = 500;
https.globalAgent.maxSockets = 500;
```
